doc: update TLS docs with X509 v3 and CA usage
input-output-hk/jormungandr pull request #2734
Opened 2020-11-19 15:21 UTC by eugene-babichenko

2020-11-20 16:05 UTC, mzabaluev approved these changes

2020-11-20 16:12 UTC, mzabaluev commented
Any idea what was missing in the `openssl` commands to get a correct X509 v3 certificate?

2020-11-20 17:44 UTC, eugene-babichenko commented
`openssl` uses v1 unless you explicitly specify v3 and all required extensions. Actually, you need to that twice: for a CSR and for an actual certificate (this is considered to be a bug by the docs BTW). Plus we need to make a root certificate + a server certificate signed by the root key.
I decided to go with `easyrsa` because using bare `openssl` commands produces a lot of boilerplate code which I think is not needed for the demonstration purposes.

2020-11-21 09:59 UTC, dkijania requested changes

2020-11-23 08:09 UTC, eugene-babichenko commented
Waiting for #2733. These docs contain a piece of documentation that specifically refers new features.

2020-11-23 08:48 UTC, merged