Expose account based vote count endpoint
input-output-hk/jormungandr pull request #3701
Opened 2021-11-23 10:48 UTC by danielSanchezQ

2021-11-24 09:25 UTC, eugene-babichenko requested changes
- Update the OpenAPI spec
- Update CHANGELOG.md

And not a request, but a note. This can be a rather heavy endpoint.

2021-11-24 09:39 UTC, danielSanchezQ commented
@eugene-babichenko yeah, I know it may be a heavy request but it is needed at some point, and I do not know how to get that information otherwise.

2021-11-24 16:35 UTC, Zeegomo commented
AFAIK, this is not actually needed publicly and should probably be hidden behind a proxy for public facing nodes.
It will only be used rarely by "administrators" (I guess with flexibility on execution time) and the impact on resources will be negligible IMHO.

2021-11-26 11:49 UTC, eugene-babichenko approved these changes

2022-01-03 09:26 UTC, merged