Add missing cors config
input-output-hk/jormungandr pull request #3726
Opened 2021-12-06 18:55 UTC by enzoc4

there are some cases where being able to set these things is necessary.

2021-12-07 07:34 UTC, eugene-babichenko approved these changes

2021-12-07 07:35 UTC, eugene-babichenko requested changes
Oops, I was too quick to approve this. You need to update the test code as well, otherwise the tests just don't compile.

2021-12-07 15:15 UTC, enzoc4 commented
I think failure is unrelated now. 

I do wonder why do we have tests for cors that are `#[cfg(windows)]` though. It shouldn't be platform dependent.

2021-12-08 08:53 UTC, eugene-babichenko approved these changes

2021-12-08 08:53 UTC, merged