add interface EvmConfigParams struct, update BlockchainConfiguration
input-output-hk/jormungandr pull request #3761
Opened 2022-01-11 09:54 UTC by Mr-Leshiy

2022-01-12 09:04 UTC, Zeegomo commented on jormungandr/Cargo.toml
> +evm = []
I think this also relies on `chaim-impl-mockchain/evm`

2022-01-12 11:13 UTC, Mr-Leshiy commented on Cargo.lock
>  source = "registry+https://github.com/rust-lang/crates.io-index"
I have update to the latest `chain-libs`, I assume that is the reason

2022-01-12 11:47 UTC, Mr-Leshiy commented on jormungandr-lib/src/interfaces/evm_params.rs
> +    #[serde(skip)]
I will add full `serde` implementation for this struct after `EvmConfigParams` on the `chain-libs` side will be updated, actually this PR.
Intention to derive Serialize/Deserialize was to have the necessary functionality and preliminary add tests and correct usage in the `BlockchainConfiguration`.

2022-01-13 09:38 UTC, Mr-Leshiy commented
need to merge first https://github.com/input-output-hk/chain-libs/pull/729

2022-01-25 14:43 UTC, eugene-babichenko requested changes
The tests are needed to be fixed, otherwise looking good, deps merged.

2022-02-01 18:05 UTC, saibatizoku approved these changes
Looks good to me, much cleaner, thanks.

2022-02-02 12:26 UTC, eugene-babichenko approved these changes

2022-02-02 13:08 UTC, merged